name: ethereum
description: An ethereum JSON RPC 2.0 client for Dart. Interfaces ethereum API calls to Dart types and vice versa.
version: 5.0.1
homepage: https://github.com/shamblett/ethereum

funding:
  - https://www.darticulate.com/#funding

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  hex: '^0.2.0'

dev_dependencies:
  test: '^1.21.5'
  build_runner: '^2.2.0'
  build_test: '^2.1.5'
  build_web_compilers: '^3.2.5'
  lints: '^2.0.0'

