name: ethereum
description: An ethereum JSON RPC 2.0 client for Dart. Interfaces ethereum API calls to Dart types and vice versa.
version: 5.0.0
homepage: https://github.com/shamblett/ethereum

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  hex: '^0.2.0'

dev_dependencies:
  test: '^1.16.8'
  pedantic: '^1.11.0'
  build_runner: '^1.12.2'
  build_test: '^2.0.0'
  build_web_compilers: '^2.16.5'

